# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "pg_config.sh"
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "forwarded_port", guest: 8000, host: 8002
  config.vm.network "forwarded_port", guest: 8080, host: 9092
  config.vm.network "forwarded_port", guest: 5000, host: 5002
  config.vm.boot_timeout = 1000
  #config.vm.provider "virtualbox" do |v|
  #   v.gui = true
  #   v.memory = 2048
  #   v.cpus = 2
  #end 	
  config.vm.network "private_network", ip: "10.11.12.53"
  config.vm.hostname = "dev2"
  config.vm.network :forwarded_port, guest: 22, host: 2224, id: "ssh", auto_correct: true
  # config.vm.box_check_update = false
  # config.vm.synced_folder "../data", "/vagrant_data"
end
