# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provision "shell", path: "pg_config.sh"
  # config.vm.box = "hashicorp/precise32"
  config.vm.box = "ubuntu/trusty32"
  config.vm.network "forwarded_port", guest: 8000, host: 8001
  config.vm.network "forwarded_port", guest: 8080, host: 9091
  config.vm.network "forwarded_port", guest: 5000, host: 5001
  config.vm.boot_timeout = 1000
  #config.vm.provider "virtualbox" do |v|
   #   v.gui = true
  #   v.memory = 2048
  # 	 v.cpus = 2
  #end 	
  config.vm.network "private_network", ip: "10.11.12.52"
  config.vm.hostname = "secondry"
  config.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh", auto_correct: true
  #config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", disabled: true
  #config.vm.network :forwarded_port, guest: 2223, host: 2223, auto_correct: true
  #config.ssh.port = 2223
end
