# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "pg_config.sh"
  config.vm.box = "bento/ubuntu-22.10"
  #config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.boot_timeout = 1000
  #config.vm.provider "virtualbox" do |v|
  #   v.gui = true
  #   v.memory = 2048
  #   v.cpus = 2
  #end 	
  config.vm.network "public_network"
  config.vm.hostname = "myvm21"
  config.vm.network :forwarded_port, guest: 22, host: 2224, id: "ssh", auto_correct: true
  # config.vm.box_check_update = false
  # config.vm.synced_folder "../data", "/vagrant_data"
end
